--task 6

CREATE SCHEMA IF NOT EXISTS BL_3NF;

CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_COUNTIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CITIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STREETS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ADDRESSES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_STORES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_VENDORS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_CATEGORIES START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_ITEMS_SCD START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_PROMOTIONS START 1;
CREATE SEQUENCE IF NOT EXISTS BL_3NF.SEQ_CE_DATES START 1;

CREATE TABLE IF NOT EXISTS BL_3NF.CE_DATES (
  DATE_ID      BIGINT NOT NULL PRIMARY KEY,  
  DATE_DT      date NOT NULL,
  DAY          integer NOT NULL,
  MONTH        integer NOT NULL,
  QUARTER      integer NOT NULL,
  YEAR         integer NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_COUNTIES (
  COUNTY_ID         BIGINT NOT NULL PRIMARY KEY,
  COUNTY_SRC_ID     VARCHAR(10) NOT NULL,
  COUNTY_NAME       varchar(20) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CITIES (
  CITY_ID           BIGINT NOT NULL PRIMARY KEY,
  CITY_SRC_ID       varchar(50) NOT NULL,
  CITY_NAME         varchar(20) NOT NULL,
  ZIP_CODE          varchar(5) NOT NULL,
  COUNTY_ID         BIGINT NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL,
  CONSTRAINT FK_CE_CITIES_CE_COUNTIES FOREIGN KEY(COUNTY_ID)
  REFERENCES BL_3NF.CE_COUNTIES(COUNTY_ID));

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STREETS (
  STREET_ID         BIGINT NOT NULL PRIMARY KEY, 
  STREET_SRC_ID     varchar(100) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ADDRESSES (
  ADDRESS_ID        BIGINT NOT NULL PRIMARY KEY,
  ADDRESS_SRC_ID    varchar(100) NOT NULL,
  HOUSE_NUMBER      integer NOT NULL,
  STREET_ID         BIGINT NOT NULL,
  CITY_ID     		BIGINT NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL,
  CONSTRAINT FK_CE_ADDRESSES_CE_STREETS FOREIGN KEY (STREET_ID)
  REFERENCES BL_3NF.CE_STREETS(STREET_ID),
  CONSTRAINT FK_CE_ADDRESSES_CE_CITIES FOREIGN KEY (CITY_ID)
  REFERENCES BL_3NF.CE_CITIES(CITY_ID));

CREATE TABLE IF NOT EXISTS BL_3NF.CE_STORES (
  STORE_ID          BIGINT NOT NULL PRIMARY KEY, 
  STORE_SRC_ID      VARCHAR(10) NOT NULL,
  STORE_NAME        varchar(100) NOT NULL,
  STORE_TYPE        varchar(10) NOT NULL,
  ADDRESS_ID        BIGINT NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL,
  CONSTRAINT FK_CE_STORES_CE_ADDRESSES FOREIGN KEY (ADDRESS_ID)
  REFERENCES BL_3NF.CE_ADDRESSES(ADDRESS_ID));

CREATE TABLE IF NOT EXISTS BL_3NF.CE_VENDORS (
  VENDOR_ID         BIGINT NOT NULL PRIMARY KEY, 
  VENDOR_SRC_ID     VARCHAR(10) NOT NULL,
  VENDOR_NAME       varchar(100) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_CATEGORIES(
  CATEGORY_ID       BIGINT NOT NULL PRIMARY KEY,
  CATEGORY_SRC_ID   VARCHAR(50) NOT NULL,
  CATEGORY_NAME     varchar(50) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_ITEMS_SCD (
  ITEM_ID              BIGINT NOT NULL PRIMARY KEY, 
  ITEM_SRC_ID          VARCHAR(10) NOT NULL,
  ITEM_NAME            varchar(100) NOT NULL,
  PACK                 integer NOT NULL,
  BOTTLE_VOLUME_ML     integer NOT NULL,
  STATE_BOTTLE_RETAIL  decimal(10,2) NOT NULL,
  STATE_BOTTLE_COST    decimal(10,2) NOT NULL,
  CATEGORY_ID          BIGINT NOT NULL,
  VENDOR_ID            BIGINT NOT NULL,

  TA_START_DT          DATE NOT NULL,
  TA_END_DT            DATE,
  TA_IS_ACTIVE         VARCHAR(1) NOT NULL,
  TA_INSERT_DT         DATE NOT NULL,
  TA_SOURCE_SYSTEM     VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY     VARCHAR(50) NOT NULL,
  CONSTRAINT FK_CE_ITEMS_SCD_CE_CATEGORIES FOREIGN KEY(CATEGORY_ID)
  REFERENCES BL_3NF.CE_CATEGORIES(CATEGORY_ID),
  CONSTRAINT FK_CE_ITEMS_SCD_CE_VENDORS FOREIGN KEY(VENDOR_ID)
  REFERENCES BL_3NF.CE_VENDORS (VENDOR_ID));

CREATE TABLE IF NOT EXISTS BL_3NF.CE_PROMOTIONS (
  PROMO_ID          BIGINT NOT NULL PRIMARY KEY, 
  PROMO_SRC_ID      VARCHAR(10) NOT NULL,
  PROMO_NAME        varchar(20) NOT NULL,
  DISCOUNT_PCT      integer,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_3NF.CE_SALES (
  DATE_ID             BIGINT NOT NULL,
  STORE_ID            BIGINT NOT NULL,
  ITEM_ID             BIGINT NOT NULL,
  PROMO_ID            BIGINT NOT NULL, 
  BOTTLES_SOLD        integer,
  SALE_DOLLARS        decimal(15,3),
  VOLUME_SOLD_LITERS  decimal(12,3),
  CONSTRAINT FK_CE_SALES_CE_DATES FOREIGN KEY(DATE_ID)
  REFERENCES BL_3NF.CE_DATES(DATE_ID),
  CONSTRAINT FK_CE_SALES_CE_STORES FOREIGN KEY(STORE_ID)
  REFERENCES BL_3NF.CE_STORES(STORE_ID),
  CONSTRAINT FK_CE_SALES_CE_ITEMS_SCD FOREIGN KEY(ITEM_ID)
  REFERENCES BL_3NF.CE_ITEMS_SCD(ITEM_ID),
  CONSTRAINT FK_CE_SALES_CE_PROMOTIONS FOREIGN KEY(PROMO_ID)
  REFERENCES BL_3NF.CE_PROMOTIONS(PROMO_ID));

  COMMIT;
  
  INSERT INTO BL_3NF.CE_DATES(DATE_ID, DATE_DT, DAY, MONTH, QUARTER, YEAR)
  VALUES (-1,'1900-01-01',-1,-1,-1,-1);

  INSERT INTO BL_3NF.CE_COUNTIES(COUNTY_ID,COUNTY_SRC_ID,COUNTY_NAME,TA_INSERT_DT,TA_UPDATE_DT,TA_SOURCE_SYSTEM,TA_SOURCE_ENTITY)
  VALUES (-1,'n.a.','n.a.','1900-01-01','1900-01-01','MANUAL','MANUAL');
  
  INSERT INTO BL_3NF.CE_CITIES(CITY_ID, CITY_SRC_ID, CITY_NAME, ZIP_CODE, COUNTY_ID, TA_INSERT_DT,TA_UPDATE_DT,TA_SOURCE_SYSTEM,TA_SOURCE_ENTITY)
  VALUES (-1,'n.a.','n.a.','n.a.',-1,'1900-01-01','1900-01-01','MANUAL','MANUAL');

  INSERT INTO BL_3NF.CE_STREETS (STREET_ID, STREET_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL');
  
  INSERT INTO BL_3NF.CE_ADDRESSES (ADDRESS_ID, ADDRESS_SRC_ID, HOUSE_NUMBER, STREET_ID, CITY_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', -1, -1, -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL');
  
  INSERT INTO BL_3NF.CE_STORES (STORE_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE, ADDRESS_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', 'n.a.', 'n.a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL');
  
  INSERT INTO BL_3NF.CE_VENDORS (VENDOR_ID, VENDOR_SRC_ID, VENDOR_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', 'n.a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL')
  ON CONFLICT DO NOTHING;
  INSERT INTO BL_3NF.CE_CATEGORIES (CATEGORY_ID, CATEGORY_SRC_ID, CATEGORY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', 'n.a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL')
  ON CONFLICT DO NOTHING;
  
  INSERT INTO BL_3NF.CE_ITEMS_SCD (ITEM_ID, ITEM_SRC_ID, ITEM_NAME, PACK, BOTTLE_VOLUME_ML, STATE_BOTTLE_RETAIL, STATE_BOTTLE_COST, CATEGORY_ID, VENDOR_ID, TA_START_DT, TA_END_DT, TA_IS_ACTIVE, TA_INSERT_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', 'n.a.', -1, -1, -1, -1, -1, -1, '1900-01-01', '9999-12-31', 'Y', '1900-01-01', 'MANUAL', 'MANUAL');
  
  INSERT INTO BL_3NF.CE_PROMOTIONS (PROMO_ID, PROMO_SRC_ID, PROMO_NAME, DISCOUNT_PCT, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
  VALUES (-1, 'n.a.', 'n.a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL');
  
   COMMIT;

-- Offline Source

INSERT INTO BL_3NF.CE_DATES (DATE_ID, DATE_DT, DAY, MONTH, QUARTER, YEAR)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_DATES'),
    src.date::DATE,
    EXTRACT(DAY FROM src.date::DATE)::INTEGER,
    EXTRACT(MONTH FROM src.date::DATE)::INTEGER,
    EXTRACT(QUARTER FROM src.date::DATE)::INTEGER,
    EXTRACT(YEAR FROM src.date::DATE)::INTEGER
FROM (
    SELECT DISTINCT date
    FROM sa_offline_sales.src_offline_sales) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_DATES t
    WHERE t.DATE_DT = src.date::DATE);

INSERT INTO BL_3NF.CE_COUNTIES (COUNTY_ID, COUNTY_SRC_ID, COUNTY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_COUNTIES'),
    COALESCE(src.county_id, 'n.a.'),
    COALESCE(src.county_name, 'n.a.'),
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT DISTINCT  
        TRIM(county_id::VARCHAR) AS county_id,
        MAX(TRIM(county_name)) AS county_name
    FROM sa_offline_sales.src_offline_sales
    WHERE county_id IS NOT NULL
    AND TRIM(county_id::VARCHAR) <> ''
    GROUP BY TRIM(county_id::VARCHAR)) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_COUNTIES t
    WHERE t.COUNTY_SRC_ID = COALESCE(NULLIF(TRIM(src.county_id::VARCHAR), ''), src.county_name, 'n.a.'));


INSERT INTO BL_3NF.CE_CITIES (CITY_ID, CITY_SRC_ID, CITY_NAME, ZIP_CODE, COUNTY_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_CITIES'),
    COALESCE(src.city_id, 'n.a.'),
    COALESCE(src.city_name, 'n.a.'),
    COALESCE(src.zip_code, 'n.a.'),
    COALESCE(fk.COUNTY_ID, -1),
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT 
        city_id, 
        MAX(city_name) as city_name, 
        MAX(zip_code) as zip_code, 
        MAX(county_id) as county_id
    FROM sa_offline_sales.src_offline_sales
    GROUP BY city_id) AS src
LEFT JOIN BL_3NF.CE_COUNTIES fk ON src.county_id = fk.COUNTY_SRC_ID
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_CITIES t
    WHERE t.CITY_SRC_ID = src.city_id);

COMMIT;

INSERT INTO BL_3NF.CE_STREETS (STREET_ID, STREET_SRC_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_STREETS'),
    src.address,
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT DISTINCT COALESCE(NULLIF(TRIM(REGEXP_REPLACE(address, '^\d+\s*', '')), ''), 'n.a.') AS address 
    FROM sa_offline_sales.src_offline_sales) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_STREETS t
    WHERE t.STREET_SRC_ID = COALESCE(NULLIF(TRIM(REGEXP_REPLACE(src.address, '^\d+\s*', '')), ''), 'n.a.'));

INSERT INTO BL_3NF.CE_ADDRESSES (ADDRESS_ID, ADDRESS_SRC_ID, HOUSE_NUMBER, STREET_ID, CITY_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
WITH clean_addresses AS (
    SELECT DISTINCT 
        address AS raw_address,
        city_id,
        NULLIF(REGEXP_REPLACE(SPLIT_PART(TRIM(address), ' ', 1), '[^0-9]', '', 'g'), '') AS h_number,
        COALESCE(NULLIF(TRIM(REGEXP_REPLACE(address, '^\d+\s*', '')), ''), 'n.a.') AS street
    FROM sa_offline_sales.src_offline_sales
    WHERE address IS NOT NULL)
SELECT DISTINCT ON (src.raw_address)
    NEXTVAL('BL_3NF.SEQ_CE_ADDRESSES'),
    COALESCE(src.raw_address, 'n.a.'),
    COALESCE(src.h_number::INTEGER, -1),
    COALESCE(st.STREET_ID, -1),
    COALESCE(cit.CITY_ID, -1),    
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM clean_addresses src
LEFT JOIN BL_3NF.CE_CITIES cit ON src.city_id = cit.CITY_SRC_ID
LEFT JOIN BL_3NF.CE_STREETS st ON st.STREET_SRC_ID = src.street
WHERE NOT EXISTS ( 
    SELECT 1
    FROM BL_3NF.CE_ADDRESSES t
    WHERE t.ADDRESS_SRC_ID = src.raw_address)
ORDER BY src.raw_address, cit.CITY_ID;

INSERT INTO BL_3NF.CE_STORES (STORE_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE, ADDRESS_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT DISTINCT ON (map.store_id::INTEGER)
    map.store_id,
    map.store_src_id,
    COALESCE(map.store_name, 'n.a.'),   
    COALESCE(src.store_type, 'n.a.'), 
    COALESCE(fk.ADDRESS_ID, -1),
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM BL_CL.T_MAP_STORES MAP
LEFT JOIN sa_offline_sales.src_offline_sales src 
    ON map.store_src_id::INTEGER = src.store_id::INTEGER
    AND map.source_system = 'sa_offline_sales'
LEFT JOIN BL_3NF.CE_ADDRESSES fk ON src.address = fk.ADDRESS_SRC_ID
WHERE map.source_system = 'sa_offline_sales'
    AND NOT EXISTS (
        SELECT 1
        FROM BL_3NF.CE_STORES t
        WHERE t.STORE_ID = map.store_id)
ORDER BY map.store_id::INTEGER;  

INSERT INTO BL_3NF.CE_VENDORS (VENDOR_ID, VENDOR_SRC_ID, VENDOR_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_VENDORS'),
    COALESCE(src.vendor_id, 'n.a.'),
    COALESCE(src.vendor_name, 'n.a.'),   
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT   
        vendor_id, 
        MAX(vendor_name) AS vendor_name
    FROM sa_offline_sales.src_offline_sales
    WHERE vendor_id IS NOT NULL
    GROUP BY vendor_id) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_VENDORS t
    WHERE t.VENDOR_SRC_ID = src.vendor_id);


INSERT INTO BL_3NF.CE_CATEGORIES (CATEGORY_ID, CATEGORY_SRC_ID, CATEGORY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_CATEGORIES'),
    COALESCE(src.category_id, 'n.a.'),
    COALESCE(src.category_name, 'n.a.'),   
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT  
        category_id, 
        MAX (category_name) AS category_name
    FROM sa_offline_sales.src_offline_sales
    WHERE category_id IS NOT NULL
    GROUP BY category_id) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_CATEGORIES t
    WHERE t.CATEGORY_SRC_ID = src.category_id);

UPDATE BL_3NF.CE_ITEMS_SCD t
SET TA_END_DT = CURRENT_DATE - 1,
    TA_IS_ACTIVE = 'N'
WHERE t.TA_IS_ACTIVE = 'Y'
    AND t.TA_SOURCE_SYSTEM = 'sa_offline_sales'
    AND EXISTS (
        SELECT 1
        FROM sa_offline_sales.src_offline_sales src
        WHERE TRIM(src.item_id) = t.ITEM_SRC_ID
        AND (
            REPLACE(src.state_bottle_retail, ',', '')::DECIMAL(10,2) <> t.STATE_BOTTLE_RETAIL OR
            REPLACE(src.state_bottle_cost, ',', '')::DECIMAL(10,2) <> t.STATE_BOTTLE_COST));

INSERT INTO BL_3NF.CE_ITEMS_SCD (
    ITEM_ID, ITEM_SRC_ID, ITEM_NAME, PACK, BOTTLE_VOLUME_ML, 
    STATE_BOTTLE_RETAIL, STATE_BOTTLE_COST, CATEGORY_ID, VENDOR_ID, 
    TA_START_DT, TA_END_DT, TA_IS_ACTIVE, TA_INSERT_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT DISTINCT ON (s.item_id)
    NEXTVAL('BL_3NF.SEQ_CE_ITEMS_SCD'),
    COALESCE(s.item_id, 'n.a.'),
    COALESCE(s.item_name, 'n.a.'),
    s.pack::INTEGER,
    s.bottle_volume_ml::INTEGER,
    REPLACE(s.state_bottle_retail, ',', '')::DECIMAL(10,2),
    REPLACE(s.state_bottle_cost, ',', '')::DECIMAL(10,2),
    COALESCE(cat.CATEGORY_ID, -1),
    COALESCE(ven.VENDOR_ID, -1),
    CURRENT_DATE, 
    '9999-12-31', 
    'Y', 
    CURRENT_DATE, 
    'sa_offline_sales', 
    'src_offline_sales'
FROM sa_offline_sales.src_offline_sales s
LEFT JOIN BL_3NF.CE_CATEGORIES cat ON s.category_id = cat.CATEGORY_SRC_ID
LEFT JOIN BL_3NF.CE_VENDORS ven ON s.vendor_id = ven.VENDOR_SRC_ID
WHERE NOT EXISTS (
    SELECT 1 FROM BL_3NF.CE_ITEMS_SCD t 
    WHERE t.ITEM_SRC_ID = s.item_id AND t.TA_IS_ACTIVE = 'Y')
ORDER BY s.item_id;


INSERT INTO BL_3NF.CE_PROMOTIONS (PROMO_ID, PROMO_SRC_ID, PROMO_NAME, DISCOUNT_PCT, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_PROMOTIONS'),
    COALESCE(src.promo_id, 'n.a.'),
    COALESCE(src.promo_name, 'n.a.'),
    COALESCE(src.discount_pct::INTEGER, -1),
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_offline_sales',
    'src_offline_sales'
FROM (
    SELECT DISTINCT  
        promo_id, 
        promo_name,
        discount_pct
    FROM sa_offline_sales.src_offline_sales) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_PROMOTIONS t
    WHERE t.PROMO_SRC_ID = src.promo_id);


INSERT INTO BL_3NF.CE_SALES (DATE_ID, STORE_ID, ITEM_ID, PROMO_ID, BOTTLES_SOLD, SALE_DOLLARS, VOLUME_SOLD_LITERS)
SELECT
    COALESCE(d.DATE_ID, -1),
    COALESCE(m.STORE_ID, -1),
    COALESCE(i.ITEM_ID, -1),
    COALESCE(p.PROMO_ID, -1),
    s.bottles_sold::INTEGER,
    COALESCE(REPLACE(NULLIF(s.sale_dollars, '#VALUE!'), ',', '')::DECIMAL(15,3), 0),
    COALESCE(REPLACE(NULLIF(s.volume_sold_liters, '#VALUE!'), ',', '')::DECIMAL(12,3), 0)
FROM sa_offline_sales.src_offline_sales s
LEFT JOIN BL_3NF.CE_DATES d ON s.date::DATE = d.DATE_DT
LEFT JOIN BL_CL.T_MAP_STORES m ON s.store_id::INTEGER = m.store_src_id AND m.source_system = 'sa_offline_sales'
LEFT JOIN BL_3NF.CE_ITEMS_SCD i ON s.item_id = i.ITEM_SRC_ID AND i.TA_IS_ACTIVE = 'Y'
LEFT JOIN BL_3NF.CE_PROMOTIONS p ON s.promo_id = p.PROMO_SRC_ID
WHERE NOT EXISTS (
    SELECT 1 
    FROM BL_3NF.CE_SALES t 
    WHERE t.DATE_ID = d.DATE_ID 
      AND t.STORE_ID = m.STORE_ID 
      AND t.ITEM_ID = i.ITEM_ID);

COMMIT; 


-- Online Source


INSERT INTO BL_3NF.CE_DATES (DATE_ID, DATE_DT, DAY, MONTH, QUARTER, YEAR)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_DATES'),
    src.date::DATE,
    EXTRACT(DAY FROM src.date::DATE)::INTEGER,
    EXTRACT(MONTH FROM src.date::DATE)::INTEGER,
    EXTRACT(QUARTER FROM src.date::DATE)::INTEGER,
    EXTRACT(YEAR FROM src.date::DATE)::INTEGER
FROM (
    SELECT DISTINCT date
    FROM sa_online_sales.src_online_sales) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_DATES t
    WHERE t.DATE_DT = src.date::DATE);

INSERT INTO BL_3NF.CE_STORES (STORE_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE, ADDRESS_ID, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT DISTINCT ON (map.store_id::INTEGER)
    map.store_id,
    map.store_src_id,
    COALESCE(map.store_name, 'n.a.'),   
    COALESCE(src.store_type, 'n.a.'), 
    -1,
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_online_sales',
    'src_online_sales'
FROM BL_CL.T_MAP_STORES MAP
LEFT JOIN sa_online_sales.src_online_sales AS src
    ON map.store_src_id::INTEGER = src.store_id::INTEGER
    AND map.source_system = 'sa_online_sales'
    WHERE map.source_system = 'sa_online_sales'
    AND NOT EXISTS (
        SELECT 1
        FROM BL_3NF.CE_STORES t
        WHERE t.STORE_ID = map.store_id)
ORDER BY map.store_id::INTEGER;  


INSERT INTO BL_3NF.CE_VENDORS (VENDOR_ID, VENDOR_SRC_ID, VENDOR_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_VENDORS'),
    COALESCE(src.vendor_id, 'n.a.'),
    COALESCE(src.vendor_name, 'n.a.'),   
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_online_sales',
    'src_online_sales'
FROM (
    SELECT   
        vendor_id, 
        MAX(vendor_name) AS vendor_name
    FROM sa_online_sales.src_online_sales
    WHERE vendor_id IS NOT NULL
    GROUP BY vendor_id) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_VENDORS t
    WHERE t.VENDOR_SRC_ID = src.vendor_id);



INSERT INTO BL_3NF.CE_CATEGORIES (CATEGORY_ID, CATEGORY_SRC_ID, CATEGORY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_CATEGORIES'),
    COALESCE(src.category_id, 'n.a.'),
    COALESCE(src.category_name, 'n.a.'),   
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_online_sales',
    'src_online_sales'
FROM (
    SELECT  
        category_id, 
        MAX (category_name) AS category_name
    FROM sa_online_sales.src_online_sales
    WHERE category_id IS NOT NULL
    GROUP BY category_id) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_CATEGORIES t
    WHERE t.CATEGORY_SRC_ID = src.category_id);

UPDATE BL_3NF.CE_ITEMS_SCD t
SET TA_END_DT = CURRENT_DATE - 1,
    TA_IS_ACTIVE = 'N'
WHERE t.TA_IS_ACTIVE = 'Y'
    AND t.TA_SOURCE_SYSTEM = 'sa_online_sales'
    AND EXISTS (
        SELECT 1
        FROM sa_online_sales.src_online_sales src
        WHERE TRIM(src.item_id) = t.ITEM_SRC_ID
        AND (
            REPLACE(src.state_bottle_retail, ',', '')::DECIMAL(10,2) <> t.STATE_BOTTLE_RETAIL OR
            REPLACE(src.state_bottle_cost, ',', '')::DECIMAL(10,2) <> t.STATE_BOTTLE_COST));

INSERT INTO BL_3NF.CE_ITEMS_SCD (
    ITEM_ID, ITEM_SRC_ID, ITEM_NAME, PACK, BOTTLE_VOLUME_ML, 
    STATE_BOTTLE_RETAIL, STATE_BOTTLE_COST, CATEGORY_ID, VENDOR_ID, 
    TA_START_DT, TA_END_DT, TA_IS_ACTIVE, TA_INSERT_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT DISTINCT ON (s.item_id)
    NEXTVAL('BL_3NF.SEQ_CE_ITEMS_SCD'),
    COALESCE(s.item_id, 'n.a.'),
    COALESCE(s.item_name, 'n.a.'),
    s.pack::INTEGER,
    s.bottle_volume_ml::INTEGER,
    REPLACE(s.state_bottle_retail, ',', '')::DECIMAL(10,2),
    REPLACE(s.state_bottle_cost, ',', '')::DECIMAL(10,2),
    COALESCE(cat.CATEGORY_ID, -1),
    COALESCE(ven.VENDOR_ID, -1),
    CURRENT_DATE, 
    '9999-12-31', 
    'Y', 
    CURRENT_DATE, 
    'sa_online_sales', 
    'src_online_sales'
FROM sa_online_sales.src_online_sales s
LEFT JOIN BL_3NF.CE_CATEGORIES cat ON s.category_id = cat.CATEGORY_SRC_ID
LEFT JOIN BL_3NF.CE_VENDORS ven ON s.vendor_id = ven.VENDOR_SRC_ID
WHERE NOT EXISTS (
    SELECT 1 FROM BL_3NF.CE_ITEMS_SCD t 
    WHERE t.ITEM_SRC_ID = s.item_id AND t.TA_IS_ACTIVE = 'Y')
ORDER BY s.item_id;


INSERT INTO BL_3NF.CE_PROMOTIONS (PROMO_ID, PROMO_SRC_ID, PROMO_NAME, DISCOUNT_PCT, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_3NF.SEQ_CE_PROMOTIONS'),
    COALESCE(src.promo_id, 'n.a.'),
    COALESCE(src.promo_name, 'n.a.'),
    COALESCE(src.discount_pct::INTEGER, -1),
    CURRENT_DATE,
    CURRENT_DATE,
    'sa_online_sales',
    'src_online_sales'
FROM (
    SELECT DISTINCT  
        promo_id, 
        promo_name,
        discount_pct
    FROM sa_online_sales.src_online_sales) AS src
WHERE NOT EXISTS (
    SELECT 1
    FROM BL_3NF.CE_PROMOTIONS t
    WHERE t.PROMO_SRC_ID = src.promo_id);


INSERT INTO BL_3NF.CE_SALES (DATE_ID, STORE_ID, ITEM_ID, PROMO_ID, BOTTLES_SOLD, SALE_DOLLARS, VOLUME_SOLD_LITERS)
SELECT
    COALESCE(d.DATE_ID, -1),
    COALESCE(m.STORE_ID, -1),
    COALESCE(i.ITEM_ID, -1),
    COALESCE(p.PROMO_ID, -1),
    s.bottles_sold::INTEGER,
    COALESCE(REPLACE(NULLIF(s.sale_dollars, '#VALUE!'), ',', '')::DECIMAL(15,3), 0),
    COALESCE(REPLACE(NULLIF(s.volume_sold_liters, '#VALUE!'), ',', '')::DECIMAL(12,3), 0)
FROM sa_online_sales.src_online_sales s
LEFT JOIN BL_3NF.CE_DATES d ON s.date::DATE = d.DATE_DT
LEFT JOIN BL_CL.T_MAP_STORES m ON s.store_id::INTEGER = m.store_src_id AND m.source_system = 'sa_online_sales'
LEFT JOIN BL_3NF.CE_ITEMS_SCD i ON s.item_id = i.ITEM_SRC_ID AND i.TA_IS_ACTIVE = 'Y'
LEFT JOIN BL_3NF.CE_PROMOTIONS p ON s.promo_id = p.PROMO_SRC_ID
WHERE NOT EXISTS (
    SELECT 1 
    FROM BL_3NF.CE_SALES t 
    WHERE t.DATE_ID = d.DATE_ID 
      AND t.STORE_ID = m.STORE_ID 
      AND t.ITEM_ID = i.ITEM_ID);

COMMIT; 