SELECT 'STORES' AS entity, 
       (SELECT count(*) FROM BL_3NF.CE_STORES WHERE STORE_ID <> -1) AS src_cnt,
       (SELECT count(*) FROM BL_DM.DIM_STORES WHERE STORE_SURR_ID <> -1) AS dm_cnt,
       (SELECT count(*) FROM BL_3NF.CE_STORES WHERE STORE_ID <> -1) - 
       (SELECT count(*) FROM BL_DM.DIM_STORES WHERE STORE_SURR_ID <> -1) AS diff

UNION ALL

SELECT 'VENDORS' AS entity, 
       (SELECT count(*) FROM BL_3NF.CE_VENDORS WHERE VENDOR_ID <> -1) AS src_cnt,
       (SELECT count(*) FROM BL_DM.DIM_VENDORS WHERE VENDOR_SURR_ID <> -1) AS dm_cnt,
       (SELECT count(*) FROM BL_3NF.CE_VENDORS WHERE VENDOR_ID <> -1) - 
       (SELECT count(*) FROM BL_DM.DIM_VENDORS WHERE VENDOR_SURR_ID <> -1) AS diff

UNION ALL

SELECT 'PROMOTIONS' AS entity, 
       (SELECT count(*) FROM BL_3NF.CE_PROMOTIONS WHERE PROMO_ID <> -1) AS src_cnt,
       (SELECT count(*) FROM BL_DM.DIM_PROMOTIONS WHERE PROMO_SURR_ID <> -1) AS dm_cnt,
       (SELECT count(*) FROM BL_3NF.CE_PROMOTIONS WHERE PROMO_ID <> -1) - 
       (SELECT count(*) FROM BL_DM.DIM_PROMOTIONS WHERE PROMO_SURR_ID <> -1) AS diff

UNION ALL

SELECT 'ITEMS (Active)' AS entity, 
       (SELECT count(*) FROM BL_3NF.CE_ITEMS_SCD WHERE ITEM_ID <> -1 AND TA_IS_ACTIVE = 'Y') AS src_cnt,
       (SELECT count(*) FROM BL_DM.DIM_ITEMS_SCD WHERE ITEM_SURR_ID <> -1 AND TA_IS_ACTIVE = 'Y') AS dm_cnt,
       (SELECT count(*) FROM BL_3NF.CE_ITEMS_SCD WHERE ITEM_ID <> -1 AND TA_IS_ACTIVE = 'Y') - 
       (SELECT count(*) FROM BL_DM.DIM_ITEMS_SCD WHERE ITEM_SURR_ID <> -1 AND TA_IS_ACTIVE = 'Y') AS diff

UNION ALL

SELECT 'SALES (Revenue)' AS entity, 
       (SELECT ROUND(SUM(SALE_DOLLARS)) FROM BL_3NF.CE_SALES) AS src_cnt,
       (SELECT ROUND(SUM(FCT_SALE_AMT_USD)) FROM BL_DM.FCT_SALES_DD) AS dm_cnt,
       (SELECT ROUND(SUM(SALE_DOLLARS)) FROM BL_3NF.CE_SALES) - 
       (SELECT ROUND(SUM(FCT_SALE_AMT_USD)) FROM BL_DM.FCT_SALES_DD) AS diff

UNION ALL

SELECT 'SALES (Qty)' AS entity, 
       (SELECT SUM(BOTTLES_SOLD) FROM BL_3NF.CE_SALES) AS src_cnt,
       (SELECT SUM(FCT_BOTTLES_SOLD_QTY) FROM BL_DM.FCT_SALES_DD) AS dm_cnt,
       (SELECT SUM(BOTTLES_SOLD) FROM BL_3NF.CE_SALES) - 
       (SELECT SUM(FCT_BOTTLES_SOLD_QTY) FROM BL_DM.FCT_SALES_DD) AS diff;