
CREATE SCHEMA IF NOT EXISTS BL_DM;

CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_STORES       START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_VENDORS      START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_ITEMS_SCD    START 1;
CREATE SEQUENCE IF NOT EXISTS BL_DM.SEQ_DIM_PROMOTIONS   START 1;

COMMIT;

CREATE TABLE IF NOT EXISTS BL_DM.DIM_DATES_DAY (
  date_id      BIGINT NOT NULL PRIMARY KEY,  
  date_dt      date NOT NULL,
  day         integer NOT NULL,
  day_of_week VARCHAR(10) NOT NULL,
  is_weekend  boolean NOT NULL,
  month        integer NOT NULL,
  quarter      integer NOT NULL,
  year         integer NOT NULL);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_STORES (
  STORE_SURR_ID     BIGINT NOT NULL PRIMARY KEY,
  STORE_SRC_ID      varchar(100) NOT NULL,
  STORE_NAME        varchar(100) NOT NULL,
  STORE_TYPE        varchar(10) NOT NULL,
  HOUSE_NUMBER      integer NOT NULL,
  CITY_NAME         varchar(20) NOT NULL,
  ZIP_CODE          varchar(5) NOT NULL,
  COUNTY_NAME       varchar(20) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_ITEMS_SCD (
  ITEM_SURR_ID          BIGINT    PRIMARY KEY    NOT NULL,
  ITEM_SRC_ID           VARCHAR(100)  NOT NULL,
  ITEM_NAME             VARCHAR(100)  NOT NULL,
  PACK                  INTEGER       NOT NULL,
  BOTTLE_VOLUME_ML      INTEGER       NOT NULL,
  STATE_BOTTLE_RETAIL   DECIMAL(10,2)  NOT NULL,
  STATE_BOTTLE_COST     DECIMAL(10,2)  NOT NULL,
  ITEM_CATEGORY_ID      BIGINT        NOT NULL,
  ITEM_CATEGORY_NAME    VARCHAR(50)   NOT NULL,
  TA_START_DT           DATE          NOT NULL,
  TA_END_DT             DATE          NOT NULL,
  TA_IS_ACTIVE          VARCHAR(1)    NOT NULL,
  TA_INSERT_DT          DATE          NOT NULL,
  TA_SOURCE_SYSTEM      VARCHAR(50)   NOT NULL,
  TA_SOURCE_ENTITY      VARCHAR(50)   NOT NULL);

CREATE TABLE IF NOT EXISTS BL_DM.DIM_VENDORS (
  VENDOR_SURR_ID         BIGINT NOT NULL PRIMARY KEY, 
  VENDOR_SRC_ID     VARCHAR(10) NOT NULL,
  VENDOR_NAME       varchar(100) NOT NULL,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS BL_DM.DIM_PROMOTIONS (
  PROMO_SURR_ID          BIGINT NOT NULL PRIMARY KEY, 
  PROMO_SRC_ID      VARCHAR(10) NOT NULL,
  PROMO_NAME        varchar(20) NOT NULL,
  DISCOUNT_PCT      integer,
  TA_INSERT_DT      date NOT NULL,
  TA_UPDATE_DT      date NOT NULL,
  TA_SOURCE_SYSTEM  VARCHAR(50) NOT NULL,
  TA_SOURCE_ENTITY  VARCHAR(50) NOT NULL);


CREATE TABLE IF NOT EXISTS BL_DM.FCT_SALES_DD (
  EVENT_DT            DATE NOT NULL,
  DATE_ID             BIGINT NOT NULL,
  STORE_SURR_ID       BIGINT NOT NULL,
  VENDOR_SURR_ID      BIGINT NOT NULL,
  ITEM_SURR_ID        BIGINT NOT NULL, 
  PROMO_SURR_ID       BIGINT NOT NULL,
  FCT_BOTTLES_SOLD_QTY        integer,
  FCT_SALE_AMT_USD        decimal(15,3),
  FCT_VOLUME_SOLD_LTR  decimal(12,3),
  FCT_PROFIT_AMT_USD     decimal(15,3),
  TA_INSERT_DT      date NOT NULL,
  CONSTRAINT FK_FCT_SALES_DD_DIM_DATES FOREIGN KEY(DATE_ID)
  REFERENCES BL_DM.DIM_DATES_DAY(DATE_ID),
  CONSTRAINT FK_FCT_SALES_DD_STORES FOREIGN KEY(STORE_SURR_ID)
  REFERENCES BL_DM.DIM_STORES(STORE_SURR_ID),
  CONSTRAINT FK_FCT_SALES_DD_DIM_VENDORS FOREIGN KEY(VENDOR_SURR_ID)
  REFERENCES BL_DM.DIM_VENDORS(VENDOR_SURR_ID),
  CONSTRAINT FK_FCT_SALES_DD_DIM_ITEMS_SCD FOREIGN KEY(ITEM_SURR_ID)
  REFERENCES BL_DM.DIM_ITEMS_SCD (ITEM_SURR_ID),
  CONSTRAINT FK_FCT_SALES_DD_DIM_PROMOTIONS FOREIGN KEY(PROMO_SURR_ID)
  REFERENCES BL_DM.DIM_PROMOTIONS(PROMO_SURR_ID));


COMMIT;


INSERT INTO BL_DM.DIM_DATES_DAY (date_id, date_dt, day, day_of_week,is_weekend, month,quarter,year)
VALUES (-1, '1900-01-01', -1, 'n.a.', FALSE, -1, -1, -1)
ON CONFLICT DO NOTHING;

INSERT INTO BL_DM.DIM_STORES(STORE_SURR_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE, HOUSE_NUMBER, CITY_NAME, ZIP_CODE, COUNTY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
VALUES (-1, 'n.a.', 'n.a.', 'n.a.', -1, 'n.a.', 'n.a.', 'n.a.','1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL')
ON CONFLICT DO NOTHING;

INSERT INTO BL_DM.DIM_VENDORS (VENDOR_SURR_ID, VENDOR_SRC_ID, VENDOR_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
VALUES (-1, 'n.a.', 'n.a.', '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL')
ON CONFLICT DO NOTHING;

INSERT INTO BL_DM.DIM_ITEMS_SCD
    (ITEM_SURR_ID, ITEM_SRC_ID, ITEM_NAME, PACK, BOTTLE_VOLUME_ML, STATE_BOTTLE_RETAIL, STATE_BOTTLE_COST, ITEM_CATEGORY_ID, ITEM_CATEGORY_NAME, TA_START_DT, TA_END_DT, TA_IS_ACTIVE, TA_INSERT_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
VALUES (-1, 'n.a.', 'n.a.', -1, -1, -1, -1, -1, 'n.a.','1900-01-01', '9999-12-31', 'Y', '1900-01-01', 'MANUAL', 'MANUAL')
ON CONFLICT DO NOTHING;

INSERT INTO BL_DM.DIM_PROMOTIONS (PROMO_SURR_ID, PROMO_SRC_ID, PROMO_NAME, DISCOUNT_PCT, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
VALUES (-1, 'n.a.', 'n.a.', -1, '1900-01-01', '1900-01-01', 'MANUAL', 'MANUAL')
ON CONFLICT DO NOTHING;

COMMIT;


INSERT INTO BL_DM.DIM_DATES_DAY (date_id, date_dt, day, day_of_week,is_weekend, month,quarter,year)
SELECT 
to_char (datum, 'YYYYMMDD'):: bigint,
datum::date,
extract(day from datum),
to_char(datum, 'TMDay'),
CASE 
        WHEN extract(isodow from datum) IN (6, 7) THEN TRUE 
        ELSE FALSE
END,
extract(month from datum),
    extract(quarter from datum),
    extract(year from datum)
FROM 
	generate_series('2024-01-01'::date, 
        '2025-12-31'::date, 
        '1 day'::interval) AS datum;


INSERT INTO BL_DM.DIM_STORES(STORE_SURR_ID, STORE_SRC_ID, STORE_NAME, STORE_TYPE, HOUSE_NUMBER, CITY_NAME, ZIP_CODE, COUNTY_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_DM.SEQ_DIM_STORES'),
    s.STORE_ID::VARCHAR,
    COALESCE(s.STORE_NAME,   'n.a.'),
    COALESCE(s.STORE_TYPE,   'n.a.'),
    COALESCE(a.HOUSE_NUMBER, -1),
    COALESCE(cit.CITY_NAME,    'n.a.'),
    COALESCE(cit.ZIP_CODE,     'n.a.'),
    COALESCE(c.COUNTY_NAME, 'n.a.'),
    CURRENT_DATE,
    CURRENT_DATE,
    'BL_3NF',
    'CE_STORES'
    FROM BL_3NF.CE_STORES as s 
    LEFT JOIN BL_3NF.CE_ADDRESSES a ON s.ADDRESS_ID=a.ADDRESS_ID
	LEFT JOIN BL_3NF.CE_CITIES cit ON a.CITY_ID= cit.CITY_ID
	LEFT JOIN BL_3NF.CE_COUNTIES c ON cit.COUNTY_ID= c.COUNTY_ID
	WHERE s.STORE_ID <> -1
	AND NOT EXISTS (
	SELECT 1 FROM BL_DM.DIM_STORES t
	WHERE t.STORE_SRC_ID = s.STORE_ID::VARCHAR);
	
UPDATE BL_DM.DIM_STORES dm
SET
  STORE_NAME = COALESCE(s.STORE_NAME,   'n.a.'),
  STORE_TYPE =  COALESCE(s.STORE_TYPE,   'n.a.'),
  HOUSE_NUMBER =  COALESCE(a.HOUSE_NUMBER, -1),
  CITY_NAME =  COALESCE(cit.CITY_NAME,    'n.a.'),
  ZIP_CODE =  COALESCE(cit.ZIP_CODE,     'n.a.'),
  COUNTY_NAME = COALESCE(c.COUNTY_NAME, 'n.a.'),
  TA_UPDATE_DT = CURRENT_DATE
 FROM BL_3NF.CE_STORES AS s
    LEFT JOIN BL_3NF.CE_ADDRESSES a ON s.ADDRESS_ID=a.ADDRESS_ID
	LEFT JOIN BL_3NF.CE_CITIES cit ON a.CITY_ID= cit.CITY_ID
	LEFT JOIN BL_3NF.CE_COUNTIES c ON cit.COUNTY_ID= c.COUNTY_ID
WHERE dm.STORE_SRC_ID = s.STORE_ID::VARCHAR
AND s.STORE_ID <> -1
 AND (
      dm.STORE_NAME   IS DISTINCT FROM COALESCE(s.STORE_NAME,   'n.a.') OR
      dm.STORE_TYPE   IS DISTINCT FROM COALESCE(s.STORE_TYPE,   'n.a.') OR
      dm.HOUSE_NUMBER IS DISTINCT FROM COALESCE(a.HOUSE_NUMBER, -1)     OR
      dm.CITY_NAME    IS DISTINCT FROM COALESCE(cit.CITY_NAME,    'n.a.') OR
      dm.ZIP_CODE     IS DISTINCT FROM COALESCE(cit.ZIP_CODE,     'n.a.') OR
      dm.COUNTY_NAME  IS DISTINCT FROM COALESCE(c.COUNTY_NAME, 'n.a.'));

INSERT INTO BL_DM.DIM_VENDORS (VENDOR_SURR_ID, VENDOR_SRC_ID, VENDOR_NAME, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT
    NEXTVAL('BL_DM.SEQ_DIM_VENDORS'),
    v.VENDOR_ID::VARCHAR,
    COALESCE(v.VENDOR_NAME, 'n.a.'),
    CURRENT_DATE,
    CURRENT_DATE,
    'BL_3NF',
    'CE_VENDORS'
    FROM BL_3NF.CE_VENDORS AS v 
    WHERE v.VENDOR_ID <> -1
      AND NOT EXISTS (
      SELECT 1 FROM BL_DM.DIM_VENDORS t
      WHERE t.VENDOR_SRC_ID = v.VENDOR_ID::VARCHAR);

UPDATE BL_DM.DIM_VENDORS dm
SET
    VENDOR_NAME  = COALESCE(v.VENDOR_NAME, 'n.a.'),
    TA_UPDATE_DT = CURRENT_DATE
FROM BL_3NF.CE_VENDORS v
WHERE dm.VENDOR_SRC_ID = v.VENDOR_ID::VARCHAR
  AND v.VENDOR_ID <> -1
  AND dm.VENDOR_NAME IS DISTINCT FROM COALESCE(v.VENDOR_NAME, 'n.a.');

INSERT INTO BL_DM.DIM_PROMOTIONS (PROMO_SURR_ID, PROMO_SRC_ID, PROMO_NAME, DISCOUNT_PCT, TA_INSERT_DT, TA_UPDATE_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
 SELECT 
    NEXTVAL('BL_DM.SEQ_DIM_PROMOTIONS'),
    p.PROMO_ID::VARCHAR,
    COALESCE(p.PROMO_NAME, 'n.a.'),
    COALESCE(p.DISCOUNT_PCT, -1),
    CURRENT_DATE,
    CURRENT_DATE,
    'BL_3NF',
    'CE_PROMOTIONS'   
    FROM BL_3NF.CE_PROMOTIONS AS p 
    WHERE p.PROMO_ID <> -1 
    AND NOT EXISTS (
      SELECT 1 FROM BL_DM.DIM_PROMOTIONS t
      WHERE t.PROMO_SRC_ID = p.PROMO_ID::VARCHAR);

UPDATE BL_DM.DIM_PROMOTIONS dm
SET
    PROMO_NAME   = COALESCE(p.PROMO_NAME, 'n.a.'),
    DISCOUNT_PCT = COALESCE(p.DISCOUNT_PCT, -1),
    TA_UPDATE_DT = CURRENT_DATE
FROM BL_3NF.CE_PROMOTIONS p
WHERE dm.PROMO_SRC_ID = p.PROMO_ID::VARCHAR 
  AND p.PROMO_ID <> -1                      
  AND (                                     
      dm.PROMO_NAME   IS DISTINCT FROM COALESCE(p.PROMO_NAME, 'n.a.') OR
      dm.DISCOUNT_PCT IS DISTINCT FROM COALESCE(p.DISCOUNT_PCT, -1));

UPDATE BL_DM.DIM_ITEMS_SCD scd
SET TA_END_DT = i.TA_START_DT - INTERVAL '1 day',
TA_IS_ACTIVE = 'N',
TA_INSERT_DT = CURRENT_DATE
FROM BL_3NF.CE_ITEMS_SCD AS i 
LEFT JOIN BL_3NF.CE_CATEGORIES cat ON i.CATEGORY_ID = cat.CATEGORY_ID
WHERE scd.ITEM_SRC_ID = i.ITEM_ID::VARCHAR
  AND scd.TA_IS_ACTIVE = 'Y'
  AND i.TA_IS_ACTIVE = 'Y'
  AND (scd.ITEM_NAME          IS DISTINCT FROM COALESCE(i.ITEM_NAME, 'n.a.') OR
      scd.PACK                IS DISTINCT FROM i.PACK OR
      scd.BOTTLE_VOLUME_ML    IS DISTINCT FROM i.BOTTLE_VOLUME_ML OR
      scd.STATE_BOTTLE_RETAIL IS DISTINCT FROM i.STATE_BOTTLE_RETAIL OR
      scd.STATE_BOTTLE_COST   IS DISTINCT FROM i.STATE_BOTTLE_COST OR
      scd.ITEM_CATEGORY_NAME  IS DISTINCT FROM COALESCE(cat.CATEGORY_NAME, 'n.a.'));
    

INSERT INTO BL_DM.DIM_ITEMS_SCD
    (ITEM_SURR_ID, ITEM_SRC_ID, ITEM_NAME, PACK, BOTTLE_VOLUME_ML, STATE_BOTTLE_RETAIL, STATE_BOTTLE_COST, ITEM_CATEGORY_ID, ITEM_CATEGORY_NAME, TA_START_DT, TA_END_DT, TA_IS_ACTIVE, TA_INSERT_DT, TA_SOURCE_SYSTEM, TA_SOURCE_ENTITY)
SELECT 
    NEXTVAL('BL_DM.SEQ_DIM_ITEMS_SCD'),
    i.ITEM_ID::VARCHAR, 
    COALESCE(i.ITEM_NAME,'n.a.'),
    i.PACK,
    i.BOTTLE_VOLUME_ML,
    i.STATE_BOTTLE_RETAIL,
    i.STATE_BOTTLE_COST,
    COALESCE(cat.CATEGORY_ID,   -1),
    COALESCE(cat.CATEGORY_NAME, 'n.a.'),
    i.TA_START_DT,
    '9999-12-31',
    'Y',
    CURRENT_DATE,
    'BL_3NF',
    'CE_ITEMS_SCD' 
    FROM BL_3NF.CE_ITEMS_SCD AS i 
    LEFT JOIN BL_3NF.CE_CATEGORIES cat ON i.CATEGORY_ID = cat.CATEGORY_ID
WHERE i.ITEM_ID <> -1
  AND i.TA_IS_ACTIVE = 'Y'
  AND NOT EXISTS (
      SELECT 1 FROM BL_DM.DIM_ITEMS_SCD t
      WHERE t.ITEM_SRC_ID  = i.ITEM_ID::VARCHAR
        AND t.TA_IS_ACTIVE = 'Y');

INSERT INTO BL_DM.FCT_SALES_DD (EVENT_DT, DATE_ID,STORE_SURR_ID, VENDOR_SURR_ID, ITEM_SURR_ID, PROMO_SURR_ID,FCT_BOTTLES_SOLD_QTY, FCT_SALE_AMT_USD,FCT_VOLUME_SOLD_LTR,  FCT_PROFIT_AMT_USD,TA_INSERT_DT)
SELECT 
	COALESCE(dd.DATE_DT,'1900-01-01'),
    COALESCE(dd.DATE_ID,-1),
    COALESCE(ds.STORE_SURR_ID,  -1),
    COALESCE(dv.VENDOR_SURR_ID, -1),
    COALESCE(di.ITEM_SURR_ID,   -1),
    COALESCE(dp.PROMO_SURR_ID,  -1),
    SUM(COALESCE(cs.BOTTLES_SOLD,       0)),
    SUM(COALESCE(cs.SALE_DOLLARS,       0)),
    SUM(COALESCE(cs.VOLUME_SOLD_LITERS, 0)),
	SUM(COALESCE(cs.SALE_DOLLARS, 0)- COALESCE(i3.STATE_BOTTLE_COST, 0) * COALESCE(cs.BOTTLES_SOLD, 0)),
    CURRENT_DATE
FROM BL_3NF.CE_SALES cs
JOIN  BL_3NF.CE_DATES d   ON cs.DATE_ID  = d.DATE_ID
LEFT JOIN BL_DM.DIM_DATES_DAY dd ON d.DATE_ID  = dd.DATE_ID
JOIN  BL_3NF.CE_STORES  s3   ON cs.STORE_ID = s3.STORE_ID
LEFT JOIN BL_DM.DIM_STORES         ds   ON s3.STORE_ID::VARCHAR = ds.STORE_SRC_ID
JOIN  BL_3NF.CE_ITEMS_SCD          i3   ON cs.ITEM_ID  = i3.ITEM_ID
                                        AND i3.TA_IS_ACTIVE = 'Y'
LEFT JOIN BL_DM.DIM_ITEMS_SCD      di   ON i3.ITEM_ID::VARCHAR  = di.ITEM_SRC_ID
                                        AND di.TA_IS_ACTIVE = 'Y'
LEFT JOIN BL_3NF.CE_VENDORS        v3   ON i3.VENDOR_ID    = v3.VENDOR_ID
LEFT JOIN BL_DM.DIM_VENDORS        dv   ON v3.VENDOR_ID::VARCHAR = dv.VENDOR_SRC_ID
JOIN  BL_3NF.CE_PROMOTIONS         p3   ON cs.PROMO_ID  = p3.PROMO_ID
LEFT JOIN BL_DM.DIM_PROMOTIONS     dp   ON p3.PROMO_ID::VARCHAR = dp.PROMO_SRC_ID
GROUP BY
    dd.DATE_DT,  dd.DATE_ID,
    ds.STORE_SURR_ID,
    dv.VENDOR_SURR_ID,
    di.ITEM_SURR_ID,
    dp.PROMO_SURR_ID
HAVING NOT EXISTS (
    SELECT 1 FROM BL_DM.FCT_SALES_DD f
    WHERE f.DATE_ID        = COALESCE(dd.DATE_ID,        -1)
      AND f.STORE_SURR_ID  = COALESCE(ds.STORE_SURR_ID,  -1)
      AND f.VENDOR_SURR_ID = COALESCE(dv.VENDOR_SURR_ID, -1)
      AND f.ITEM_SURR_ID   = COALESCE(di.ITEM_SURR_ID,   -1)
      AND f.PROMO_SURR_ID  = COALESCE(dp.PROMO_SURR_ID,  -1));

COMMIT;
